use agentsync_core::{Identity, Pubkey, USER_IDENTITY_FILENAME, USER_STATE_DIR};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct ConfigFile {
    #[serde(default)]
    pub vault: VaultSection,
    #[serde(default)]
    pub identity: IdentitySection,
    #[serde(default)]
    pub sync: SyncSection,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct VaultSection {
    pub id: Option<String>,
    /// Human-readable display name for this vault. Auto-generated by `init`
    /// (defaults to the vault directory's basename) and overridable with
    /// `--name`. Sent in the handshake so cloning peers can default the
    /// local directory name.
    pub name: Option<String>,
    pub rendezvous_url: Option<String>,
    /// TOFU-pinned hub identity pubkey (Phase 4). Optional in Phases 1-3.
    pub hub_pubkey: Option<String>,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct IdentitySection {
    /// Path to the on-disk identity secret (default: `.agentsync/identity`).
    /// Relative paths are resolved against the vault root.
    pub path: Option<String>,
    /// Phase 3: ssh-agent socket path.
    pub agent_socket: Option<String>,
    /// Phase 3: pubkey selecting which identity in the agent to use.
    pub agent_pubkey: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncSection {
    #[serde(default = "default_extensions")]
    pub extensions: Vec<String>,
    #[serde(default)]
    pub include: Vec<String>,
    #[serde(default = "default_attachment_max")]
    pub attachment_max_bytes: u64,
    #[serde(default = "default_text_max")]
    pub text_file_max_bytes: u64,
    #[serde(default = "default_retention")]
    pub log_retention_days: u32,
}

fn default_extensions() -> Vec<String> {
    vec!["md".into(), "markdown".into()]
}
fn default_attachment_max() -> u64 {
    10 * 1024 * 1024
}
fn default_text_max() -> u64 {
    1 * 1024 * 1024
}
fn default_retention() -> u32 {
    30
}

impl Default for SyncSection {
    fn default() -> Self {
        Self {
            extensions: default_extensions(),
            include: Vec::new(),
            attachment_max_bytes: default_attachment_max(),
            text_file_max_bytes: default_text_max(),
            log_retention_days: default_retention(),
        }
    }
}

impl SyncSection {
    pub fn to_bind_options(&self) -> agentsync_core::BindOptions {
        let mut include: Vec<String> = self
            .extensions
            .iter()
            .map(|e| format!("**/*.{}", e.trim_start_matches('.').to_ascii_lowercase()))
            .collect();
        for extra in &self.include {
            if !include.contains(extra) {
                include.push(extra.clone());
            }
        }
        let text_extensions = self
            .extensions
            .iter()
            .map(|e| e.trim_start_matches('.').to_ascii_lowercase())
            .collect();
        agentsync_core::BindOptions {
            include_patterns: include,
            text_extensions,
            attachment_max_bytes: self.attachment_max_bytes,
            text_file_max_bytes: self.text_file_max_bytes,
        }
    }
}

pub fn config_path(vault_root: &Path) -> PathBuf {
    vault_root.join(".agentsync").join("config.toml")
}

pub fn read_or_default(vault_root: &Path) -> Result<ConfigFile> {
    let path = config_path(vault_root);
    if !path.exists() {
        return Ok(ConfigFile::default());
    }
    let bytes = std::fs::read(&path).with_context(|| format!("read {}", path.display()))?;
    let s = std::str::from_utf8(&bytes).context("config.toml not valid utf-8")?;
    let cfg: ConfigFile = toml::from_str(s).with_context(|| format!("parse {}", path.display()))?;
    Ok(cfg)
}

pub fn write(vault_root: &Path, cfg: &ConfigFile) -> Result<()> {
    let dir = vault_root.join(".agentsync");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("config.toml");
    let bytes = toml::to_string_pretty(cfg)?;
    std::fs::write(&path, bytes)?;
    Ok(())
}

/// Resolve the configured identity-secret path. Resolution order:
///
///   1. `[identity] path` from `config.toml` (relative paths resolve against
///      the vault root; absolute paths are used as-is).
///   2. `~/<USER_STATE_DIR>/<USER_IDENTITY_FILENAME>` — the user-level
///      default, shared across all of this user's vaults (mirrors SSH's
///      `~/.ssh/id_ed25519` convention).
pub fn identity_path(vault_root: &Path, cfg: &ConfigFile) -> PathBuf {
    if let Some(rel) = cfg.identity.path.as_deref() {
        let p = PathBuf::from(rel);
        return if p.is_absolute() {
            p
        } else {
            vault_root.join(p)
        };
    }
    user_identity_default()
}

/// `~/.agentsync/id_ed25519`, with `$HOME` resolution. Falls back to a
/// path under the vault root if `$HOME` is unset (rare; mostly relevant
/// in restricted CI environments).
pub fn user_identity_default() -> PathBuf {
    let home = std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    home.join(USER_STATE_DIR).join(USER_IDENTITY_FILENAME)
}

/// Resolve the configured identity. Discovery rules per AUTH.md Phase 3:
/// CLI flag > config field > $SSH_AUTH_SOCK env var (only when both
/// `agent_pubkey` is set and the agent socket can be located).
///
/// File backend is the default; agent backend is selected when
/// `[identity] agent_pubkey` is set in config or via the
/// `--identity-agent-pubkey` flag.
pub fn resolve_identity(vault_root: &Path, cfg: &ConfigFile) -> Result<Identity> {
    if let Some(agent_pubkey_str) = cfg.identity.agent_pubkey.as_deref() {
        let agent_pk = Pubkey::from_ssh_string(agent_pubkey_str).map_err(|e| anyhow::anyhow!(e))?;
        let socket = resolve_agent_socket(cfg)?;
        return Ok(Identity::from_agent(socket, agent_pk));
    }

    let path = identity_path(vault_root, cfg);
    if !path.exists() {
        anyhow::bail!(
            "identity file not found at {}. \
             Run `agentsync key generate` to create one, then add the printed pubkey \
             to authorized_keys before connecting.",
            path.display()
        );
    }
    Identity::load_from_file(&path).map_err(|e| anyhow::anyhow!(e))
}

/// Parse the optional `[vault] hub_pubkey` field into a Pubkey. Returns
/// `None` if the field is absent. Errors on malformed input — better to
/// fail loud than silently strip the pin.
pub fn resolve_hub_pubkey(cfg: &ConfigFile) -> Result<Option<Pubkey>> {
    match cfg.vault.hub_pubkey.as_deref() {
        None => Ok(None),
        Some(s) => Pubkey::from_ssh_string(s)
            .map(Some)
            .map_err(|e| anyhow::anyhow!(e)),
    }
}

fn resolve_agent_socket(cfg: &ConfigFile) -> Result<PathBuf> {
    if let Some(s) = cfg.identity.agent_socket.as_deref() {
        return Ok(PathBuf::from(s));
    }
    let env = std::env::var("SSH_AUTH_SOCK").context(
        "agent identity selected but no [identity] agent_socket and \
         $SSH_AUTH_SOCK is unset",
    )?;
    Ok(PathBuf::from(env))
}
