[vault]
id = "46cd5031-40c9-458d-9a2b-ab77a5f2763e"
rendezvous_url = "ws://192.168.86.28:1234"
hub_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvrJricUG0Xn/AtovnAoVc0ml6RFrWbjbtIGB3HF/Aq"

[identity]

[sync]
extensions = [
    "md",
    "markdown",
]
exclude = [
    "**/.git/**",
    "**/node_modules/**",
    "**/.DS_Store",
    "**/.agentsync/**",
]
include = []
attachment_max_bytes = 10485760
text_file_max_bytes = 1048576
log_retention_days = 30
